### ISSUE TITLE
21.11 failure

### ISSUE THREAD

**Issue by JacobSandin** [Libriotech/ftp2koha#7]
I do not know if it is version specific, however I needed to fix the following for it to run.

in yaml configfile I had to add 
`skip_items: 0`

And in ftp2koha.pl I hade to change 
`use Koha::DateUtils;`
to
`use Koha::DateUtils qw( output_pref dt_from_string );`

Kind regards
Jacob

**Comment by MagnusEnger** [comment]
Thanks for reporting! These problems have been fixed in:

* 2aebb41e94bc6cfb717fc0209a9635940b6b898f
* 4abadde5d3ab357c422134a044c71f49c05f14ee
